"use client"

import * as React from "react"

import { Briefcase, Clock, CurrencyDollar, MapPin } from "@phosphor-icons/react"

interface Job {
  title: string
  company: string
  skills: string
  location: string
  type: string
  minExperience: number
  maxExperience: number
  salary: string
  link: string
}

interface Props {}

const JobPosts: React.FC<Props> = () => {
  return (
    <section className="max-w-5xl mx-auto grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 font-mono mb-20">
      {jobs.map((job, index) => (
        <a
          key={index}
          href={job.link}
          target="_blank"
          rel="noopener noreferrer"
          className="border border-zinc-600 p-4 hover:border-zinc-500 transition-colors group"
        >
          <p className="mb-1.5 text-zinc-200">{job.title}</p>
          <p className="mb-4 text-sm text-zinc-500">{job.company}</p>
          <p className="mb-8 text-sm text-zinc-500">{job.skills}</p>
          <div className="mb-4 grid grid-cols-2 text-sm text-zinc-200">
            <p className="flex gap-1.5 items-center">
              <MapPin size={14} />
              <span>{job.location}</span>
            </p>
            <p className="flex gap-1.5 items-center">
              <Clock size={14} />
              <span>{job.type}</span>
            </p>
            <p className="flex gap-1.5 items-center">
              <Briefcase size={14} />
              <span>
                {job.minExperience}-{job.maxExperience} years
              </span>
            </p>
            <p className="flex gap-1.5 items-center">
              <CurrencyDollar size={14} />
              <span>{job.salary}</span>
            </p>
          </div>
          <button className="text-sm text-zinc-200 bg-zinc-800 group-hover:bg-zinc-700 transition-colors group-focus:bg-zinc-700 outline-none w-full py-2 cursor-pointer">
            Apply
          </button>
        </a>
      ))}
    </section>
  )
}

export default JobPosts

const jobs: Job[] = [
  {
    title: "Frontend Engineer",
    company: "Vercel",
    skills:
      "React, TypeScript, Tailwind CSS, Next.js, Node.js, Express, MongoDB",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$100k-$120k",
    link: "https://vercel.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "PostHog",
    skills: "Python, Django, PostgreSQL, Redis, AWS, Docker, Kubernetes",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$120k-$140k",
    link: "https://posthog.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Raycast",
    skills: "Swift, TypeScript, React, Node.js, SQLite, macOS APIs",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://raycast.com/careers",
  },
  {
    title: "Senior Frontend Developer",
    company: "Stripe",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://stripe.com/careers",
  },
  {
    title: "Backend Systems Engineer",
    company: "Cloudflare",
    skills: "Go, Rust, C++, Linux, Network Protocols, Distributed Systems",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$150k-$170k",
    link: "https://cloudflare.com/careers",
  },
  {
    title: "Full Stack Developer",
    company: "Notion",
    skills: "React, TypeScript, Node.js, PostgreSQL, Redis, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$140k-$160k",
    link: "https://notion.com/careers",
  },
  {
    title: "Frontend Architect",
    company: "GitHub",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$180k-$200k",
    link: "https://github.com/careers",
  },
  {
    title: "Backend Developer",
    company: "Discord",
    skills: "Python, Django, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$130k-$150k",
    link: "https://discord.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Figma",
    skills: "React, TypeScript, Node.js, PostgreSQL, Redis, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$140k-$160k",
    link: "https://figma.com/careers",
  },
  {
    title: "Senior Backend Engineer",
    company: "MongoDB",
    skills: "Go, Rust, C++, Linux, Network Protocols, Distributed Systems",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://mongodb.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Linear",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://linear.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Supabase",
    skills: "PostgreSQL, Rust, Go, TypeScript, Docker, Kubernetes",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://supabase.com/careers",
  },
  {
    title: "Full Stack Developer",
    company: "Vercel",
    skills: "React, TypeScript, Node.js, PostgreSQL, Redis, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://vercel.com/careers",
  },
  {
    title: "Senior Frontend Engineer",
    company: "PostHog",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$150k-$170k",
    link: "https://posthog.com/careers",
  },
  {
    title: "Backend Developer",
    company: "Raycast",
    skills: "Swift, TypeScript, Node.js, SQLite, macOS APIs",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$120k-$140k",
    link: "https://raycast.com/careers",
  },
  {
    title: "DevOps Engineer",
    company: "Netlify",
    skills: "AWS, Docker, Kubernetes, Terraform, Ansible, CI/CD, GitLab",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://netlify.com/careers",
  },
  {
    title: "Site Reliability Engineer",
    company: "DigitalOcean",
    skills: "Go, Kubernetes, Prometheus, Grafana, Terraform, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$150k-$170k",
    link: "https://digitalocean.com/careers",
  },
  {
    title: "Mobile Developer",
    company: "Heroku",
    skills: "React Native, TypeScript, Redux, Jest, Detox, iOS, Android",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://heroku.com/careers",
  },
  {
    title: "iOS Developer",
    company: "AWS",
    skills: "Swift, SwiftUI, Core Data, CloudKit, AWS SDK, XCTest",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://aws.amazon.com/careers",
  },
  {
    title: "Android Developer",
    company: "Google",
    skills: "Kotlin, Android, Jetpack Compose, Room, Firebase, Material Design",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://careers.google.com",
  },
  {
    title: "React Developer",
    company: "Microsoft",
    skills: "React, TypeScript, Redux, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://careers.microsoft.com",
  },
  {
    title: "Node.js Developer",
    company: "Meta",
    skills: "Node.js, Express, TypeScript, GraphQL, MongoDB, Redis",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$140k-$160k",
    link: "https://meta.com/careers",
  },
  {
    title: "Python Developer",
    company: "Apple",
    skills: "Python, Django, Flask, PostgreSQL, Redis, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://apple.com/careers",
  },
  {
    title: "Go Developer",
    company: "Netflix",
    skills: "Go, gRPC, Protocol Buffers, Docker, Kubernetes, AWS",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$160k-$180k",
    link: "https://netflix.com/careers",
  },
  {
    title: "Rust Developer",
    company: "Twitter",
    skills: "Rust, WebAssembly, Systems Programming, Cargo, Tokio",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://twitter.com/careers",
  },
  {
    title: "Java Developer",
    company: "LinkedIn",
    skills: "Java, Spring Boot, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://linkedin.com/careers",
  },
  {
    title: "C++ Developer",
    company: "Reddit",
    skills: "C++, CMake, STL, Boost, Linux, Systems Programming",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$150k-$170k",
    link: "https://reddit.com/careers",
  },
  {
    title: "Systems Engineer",
    company: "Twitch",
    skills: "Go, Rust, Linux, Network Protocols, Distributed Systems",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$150k-$170k",
    link: "https://twitch.tv/careers",
  },
  {
    title: "Infrastructure Engineer",
    company: "Spotify",
    skills: "Terraform, Kubernetes, AWS, Prometheus, Grafana, Go",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://spotify.com/careers",
  },
  {
    title: "Cloud Engineer",
    company: "Airbnb",
    skills: "AWS, Azure, GCP, Terraform, Kubernetes, CI/CD",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://airbnb.com/careers",
  },
  {
    title: "Security Engineer",
    company: "Uber",
    skills: "Security, Python, Go, AWS, Kubernetes, SIEM",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$160k-$180k",
    link: "https://uber.com/careers",
  },
  {
    title: "Data Engineer",
    company: "Lyft",
    skills: "Python, Spark, Kafka, Snowflake, Airflow, dbt",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://lyft.com/careers",
  },
  {
    title: "Machine Learning Engineer",
    company: "DoorDash",
    skills: "Python, PyTorch, TensorFlow, AWS, Kubernetes, MLOps",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$160k-$180k",
    link: "https://doordash.com/careers",
  },
  {
    title: "AI Engineer",
    company: "Slack",
    skills: "Python, PyTorch, TensorFlow, AWS, Kubernetes, MLOps",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$160k-$180k",
    link: "https://slack.com/careers",
  },
  {
    title: "Blockchain Developer",
    company: "Zoom",
    skills: "Solidity, Web3.js, Ethereum, Smart Contracts, TypeScript",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://zoom.com/careers",
  },
  {
    title: "Web3 Developer",
    company: "Dropbox",
    skills: "Solidity, Web3.js, Ethereum, Smart Contracts, TypeScript",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://dropbox.com/careers",
  },
  {
    title: "Smart Contract Developer",
    company: "Box",
    skills: "Solidity, Web3.js, Ethereum, Smart Contracts, TypeScript",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$150k-$170k",
    link: "https://box.com/careers",
  },
  {
    title: "Game Developer",
    company: "Adobe",
    skills: "Unity, C#, Game Development, 3D Graphics, Physics",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://adobe.com/careers",
  },
  {
    title: "AR/VR Developer",
    company: "Autodesk",
    skills: "Unity, C#, AR/VR Development, 3D Graphics, Physics",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://autodesk.com/careers",
  },
  {
    title: "Embedded Developer",
    company: "Salesforce",
    skills: "C, C++, RTOS, ARM, Embedded Systems, Linux",
    location: "Remote",
    type: "Full-time",
    minExperience: 5,
    maxExperience: 7,
    salary: "$150k-$170k",
    link: "https://salesforce.com/careers",
  },
  {
    title: "Senior Frontend Engineer",
    company: "HubSpot",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://hubspot.com/careers",
  },
  {
    title: "Lead Backend Engineer",
    company: "Shopify",
    skills: "Ruby, Rails, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$180k-$200k",
    link: "https://shopify.com/careers",
  },
  {
    title: "Principal Engineer",
    company: "Square",
    skills: "Java, Spring Boot, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$200k-$220k",
    link: "https://square.com/careers",
  },
  {
    title: "Staff Engineer",
    company: "Coinbase",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$200k-$220k",
    link: "https://coinbase.com/careers",
  },
  {
    title: "Architect",
    company: "Binance",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$200k-$220k",
    link: "https://binance.com/careers",
  },
  {
    title: "Technical Lead",
    company: "Kraken",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$180k-$200k",
    link: "https://kraken.com/careers",
  },
  {
    title: "Engineering Manager",
    company: "Robinhood",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$200k-$220k",
    link: "https://robinhood.com/careers",
  },
  {
    title: "CTO",
    company: "Plaid",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 10,
    maxExperience: 12,
    salary: "$300k-$350k",
    link: "https://plaid.com/careers",
  },
  {
    title: "Senior Software Engineer",
    company: "Stripe",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://stripe.com/careers",
  },
  {
    title: "Lead Software Engineer",
    company: "Square",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 8,
    maxExperience: 10,
    salary: "$180k-$200k",
    link: "https://square.com/careers",
  },
  {
    title: "Senior Developer",
    company: "PayPal",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://paypal.com/careers",
  },
  {
    title: "Full Stack Developer",
    company: "Venmo",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://venmo.com/careers",
  },
  {
    title: "Backend Developer",
    company: "Wise",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://wise.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Datadog",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://datadog.com/careers",
  },
  {
    title: "Senior Backend Engineer",
    company: "New Relic",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 6,
    maxExperience: 8,
    salary: "$160k-$180k",
    link: "https://newrelic.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Splunk",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://splunk.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Elastic",
    skills: "Java, Spring Boot, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://elastic.co/careers",
  },
  {
    title: "Frontend Engineer",
    company: "CockroachDB",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://cockroachlabs.com/careers",
  },
  {
    title: "Full Stack Developer",
    company: "PlanetScale",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://planetscale.com/careers",
  },
  {
    title: "Backend Developer",
    company: "Firebase",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://firebase.google.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Fastly",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://fastly.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Akamai",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://akamai.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "CloudFront",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://aws.amazon.com/careers",
  },
  {
    title: "Backend Developer",
    company: "Linode",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://linode.com/careers",
  },
  {
    title: "Frontend Engineer",
    company: "Railway",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://railway.app/careers",
  },
  {
    title: "Full Stack Developer",
    company: "GitLab",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://gitlab.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Bitbucket",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://bitbucket.org/careers",
  },
  {
    title: "Frontend Developer",
    company: "CircleCI",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://circleci.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "GitHub Actions",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://github.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Jenkins",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://jenkins.io/careers",
  },
  {
    title: "Backend Developer",
    company: "Travis CI",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://travis-ci.com/careers",
  },
  {
    title: "Frontend Engineer",
    company: "TeamCity",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://jetbrains.com/careers",
  },
  {
    title: "Full Stack Developer",
    company: "Bamboo",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://atlassian.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "GoCD",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://gocd.org/careers",
  },
  {
    title: "Frontend Developer",
    company: "Concourse",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://concourse-ci.org/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Docker",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://docker.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Kubernetes",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://kubernetes.io/careers",
  },
  {
    title: "Frontend Developer",
    company: "Terraform",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://hashicorp.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Ansible",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://redhat.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Puppet",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://puppet.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Chef",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://chef.io/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "SaltStack",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://saltstack.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Vagrant",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://hashicorp.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Packer",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://hashicorp.com/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Consul",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://hashicorp.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Vue",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://vuejs.org/careers",
  },
  {
    title: "Frontend Developer",
    company: "Angular",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://angular.io/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Svelte",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://svelte.dev/careers",
  },
  {
    title: "Backend Engineer",
    company: "Next.js",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://vercel.com/careers",
  },
  {
    title: "Frontend Developer",
    company: "Nuxt.js",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://nuxtjs.org/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "Remix",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://remix.run/careers",
  },
  {
    title: "Backend Engineer",
    company: "Astro",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://astro.build/careers",
  },
  {
    title: "Frontend Developer",
    company: "Qwik",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://qwik.builder.io/careers",
  },
  {
    title: "Full Stack Engineer",
    company: "SolidJS",
    skills: "React, Node.js, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://solidjs.com/careers",
  },
  {
    title: "Backend Engineer",
    company: "Elixir",
    skills: "Go, Rust, PostgreSQL, Redis, AWS, Docker",
    location: "Remote",
    type: "Full-time",
    minExperience: 4,
    maxExperience: 6,
    salary: "$140k-$160k",
    link: "https://elixir-lang.org/careers",
  },
  {
    title: "Frontend Developer",
    company: "Rails",
    skills: "React, TypeScript, GraphQL, Jest, Webpack, CSS-in-JS",
    location: "Remote",
    type: "Full-time",
    minExperience: 3,
    maxExperience: 5,
    salary: "$130k-$150k",
    link: "https://rubyonrails.org/careers",
  },
]
